server:
  port: 8080

spring:
  application:
    name: vuln-backend
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://192.168.30.12:3306/vulnshop?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  
  
  # Redis配置
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}
    password: ${SPRING_REDIS_PASSWORD:}
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  
  # SQL初始化配置（临时禁用）
  sql:
    init:
      mode: never

# MinIO配置
minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  bucket-name: ${MINIO_BUCKET_NAME:vulnshop}

# 关键漏洞：Actuator未授权访问
management:
  endpoints:
    web:
      exposure:
        include: "*"  # 暴露所有端点，包括敏感信息
  endpoint:
    health:
      show-details: always
    env:
      show-values: always
    beans:
      enabled: true
    configprops:
      enabled: true
    loggers:
      enabled: true

logging:
  level:
    com.vuln: DEBUG
